# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize:
    person.anne_therese:
      entity_picture: "/local/mushrooms.jpeg"

# Text to speech
tts:
  - platform: google_translate

climate:
  - platform: demo

light:
  - platform: demo
  - platform: switch
    name: Christmas Tree Lights
    entity_id: switch.decorative_lights

switch:
  - platform: demo

cover:
  - platform: demo

media_player:
  - platform: demo

device_tracker:
  - platform: demo

sensor:
  - platform: demo

binary_sensor:
  - platform: demo

weather:
  - platform: demo

fan:
  - platform: demo

lock:
  - platform: demo

humidifier:
  - platform: demo
  
person:
  - name: Anne Therese
    id: anne_therese
    device_trackers:
      - device_tracker.demo_anne_therese

zone:
  - name: Office
    latitude: 52.37451608362128
    longitude: 4.888106097860146
    radius: 50
    icon: mdi:office-building

vacuum:
  - platform: demo

update:
  - platform: demo
  
alarm_control_panel:
  - platform: manual
    name: Alarm panel 1
    arming_time: 5
  - platform: manual
    name: Alarm panel 2
    arming_time: 5
  - platform: manual
    name: Alarm panel code
    code: 1234
    arming_time: 5
  - platform: manual
    name: Alarm panel text code
    code: azerty
    arming_time: 5
  - platform: template
    panels:
      templated_alarm_panel:
        value_template: "{{ states('alarm_control_panel.alarm_panel_1') }}"
        code_format: no_code
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          target:
            entity_id:
              - alarm_control_panel.alarm_panel_1
              - alarm_control_panel.alarm_panel_2
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          target:
            entity_id:
              - alarm_control_panel.alarm_panel_1
              - alarm_control_panel.alarm_panel_2
        disarm:
          service: alarm_control_panel.alarm_disarm
          target:
            entity_id:
              - alarm_control_panel.alarm_panel_1
              - alarm_control_panel.alarm_panel_2

lovelace: !include ui-lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
#   development_repo: /workspaces/home-assistant-frontend